package dl;
// Generated 22-oct-2017 13:17:01 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * Forum generated by hbm2java
 */
@Entity
@NamedQueries({
	@NamedQuery(name="Forum.findAll", query="SELECT s FROM Forum s"),
	@NamedQuery(name="Forum.findUser", query="SELECT s FROM Forum s WHERE s.user.id= :user"),
	@NamedQuery(name="Forum.findFromDate", query="SELECT s FROM Forum s WHERE s.date>= :date"),
	@NamedQuery(name="Forum.findFromDateAndUser", query="SELECT s FROM Forum s WHERE s.user.id= :user AND s.date>= :date"),
	@NamedQuery(name="Forum.findFromQuestAndLogin", query="SELECT s FROM Forum s WHERE s.user.login= :login AND s.question= :question")
})
@Table(name = "Forum")
public class Forum implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String title;
	private User user;
	private String question;
	private String answer;
	private String teacher;
	private int date;

	public Forum() {
	}

	public Forum(User user, String title, String question, String answer, String teacher, int date) {
		this.user = user;
		this.question = question;
		this.answer = answer;
		this.teacher = teacher;
		this.date = date;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}
	
	@Column(name = "title", nullable = false)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "question", nullable = false)
	public String getQuestion() {
		return this.question;
	}

	public void setQuestion(String question) {
		this.question = question;
	}
	
	@Column(name = "answer", nullable = true)
	public String getAnswer() {
		return this.answer;
	}

	public void setAnswer(String answer) {
		this.answer = answer;
	}

	@Column(name = "teacher", nullable = true)
	public String getTeacher() {
		return this.teacher;
	}

	public void setTeacher(String teacher) {
		this.teacher = teacher;
	}

	@Column(name = "date", nullable = false)
	public int getDate() {
		return this.date;
	}

	public void setDate(int date) {
		this.date = date;
	}

}
